
title: Your awesome title
email: k.chausheva@gmail.com
description: A FrontEnd WannaBe.
baseurl: "/CSS-Advanced-Final-Project" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KristinaChausheva

# Build settings
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
