
title: Portfolio
email: k.chausheva@gmail.com
phone-number: +359883222003
description: Front-End Dev WannaBe, AI Enthusiast, IoT Maniac
destination: docs
#baseurl: "/CSS-Advanced-Final-Project"
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KristinaChausheva

# Build settings
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules
  - node_modules/
  - package.json
  - package-lock.json
  - gulpfile.js
   - docs
